import type { SxStyles } from '@/shared/types'

export const messageBubbleStyles = {
  row: {
    display: 'flex',
    px: 2,
    py: 0.25,
  },
  rowIn: { justifyContent: 'flex-start' },
  rowOut: { justifyContent: 'flex-end' },
  bubble: {
    maxWidth: 'min(72%, 560px)',
    px: 1.75,
    py: 1,
    borderRadius: 3,
    fontSize: 14,
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    position: 'relative',
  },
  bubbleIn: {
    bgcolor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
    borderBottomLeftRadius: 6,
  },
  bubbleOut: {
    bgcolor: '#e0e7ff',
    color: 'text.primary',
    borderBottomRightRadius: 6,
  },
  /** Не отправлялось в Telegram: сухой прогон или черновик. */
  bubbleGhost: {
    bgcolor: 'transparent',
    border: '1px dashed',
    borderColor: 'primary.main',
    color: 'text.secondary',
    borderBottomRightRadius: 6,
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 0.5,
    mt: 0.5,
  },
  meta: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 0.75,
    mt: 0.25,
    fontSize: 11,
    color: 'text.secondary',
  },
  aiTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.25,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.04em',
    color: 'primary.main',
    '& svg': { fontSize: 12 },
  },
  mediaTag: {
    display: 'inline-flex',
    alignItems: 'center',
    mr: 0.5,
    verticalAlign: 'middle',
    color: 'text.secondary',
    '& svg': { fontSize: 14 },
  },
  readMark: {
    display: 'inline-flex',
    alignItems: 'center',
    color: 'text.disabled',
    '& svg': { fontSize: 14 },
  },
  readMarkRead: {
    color: 'primary.main',
  },
  firstBadge: {
    mb: 0.75,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 0.75,
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    color: 'primary.main',
  },
} satisfies SxStyles
